version: '3.1'


services:
 mainDB:
  image: postgres:15.0
  container_name: mainDB
  ports:
   - "8001:5432"
  environment:
    - POSTGRES_USER=branda
    - POSTGRES_PASSWORD=branda
    - POSTGRES_DB=branda
  volumes:
    - ./data:/var/lib/postgresql/data
  testDB:
    image: postgres:15.0
    container_name: testDB
    ports:
    - "8001:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./test:/var/lib/postgresql/data

volumes:
  data: